version: "2"
services:
  prod:
    image: jamesgood626/simple-chat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  web:
    image: jamesgood626/simple-chat
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    environment:
      LOCALHOST: host.docker.internal
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/opt/app
    environment:
      LOCALHOST: host.docker.internal
    command: ["npm", "run", "test"]
